name: tiamo_reborn
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  provider: ^6.1.5
  bloc: ^9.0.0
  flutter_bloc: ^9.1.1
  flutter_svg: ^2.2.0
  go_router: ^16.2.0
  flutter_dotenv: ^5.2.1
  flutter_localization: ^0.3.3
  logger: ^2.6.1
  swipe_refresh: ^1.1.2
  cached_network_image: ^3.4.1
  table_calendar: ^3.2.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  record: ^6.1.1
  path_provider: ^2.1.5


dev_dependencies:
  flutter_test:
    sdk: flutter

  json_serializable: ^6.10.0
  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
